# image will be published to ghcr.io/<user>/<name>
name: personal-blue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
                       # put configuration files you want in /usr/etc/ inside the image
                       # while putting files in /etc/ is done on booted system by system administrators.
                       # read more about this in files module reference.

  - type: rpm-ostree
    repos:
      - https://repository.mullvad.net/rpm/beta/mullvad.repo # mullvad
      - https://repo.librewolf.net/librewolf.repo # librewolf

    keys:

    optfix:
      - Mullvad # mullvad-vpn

    install:
      - alacritty
      - k3b
      - libburn
      - cdrskin
      - distrobox
      - yt-dlp
      - qemu
      - virt-manager
      - keepassxc
      - krita
      - https://launchpad.net/veracrypt/trunk/1.26.7/+download/veracrypt-1.26.7-CentOS-8-x86_64.rpm # Veracrypt GUI
      - https://github.com/VSCodium/vscodium/releases/download/1.94.2.24286/codium-1.94.2.24286-el8.x86_64.rpm # VS Codium
      - neovim
      - dotnet-sdk-8.0
      - lua
      - librewolf
      - mullvad-vpn
      - gwenview
      - okular
      - kcalc
      - celluloid
     # - HandBrake
      - pv
      - libvirt
      - tmux
      - rust 
      - cargo
      - zig
      - zig-libs
      - zig-doc
      - lld
      - tldr
      - apitrace
      - xz
      - xz-lzma-compat
      - xz-libs
      - xz-static 
      - cronie
      - cronie-anacron
      
      # SDL
      - SDL2
      - SDL2-devel
      - SDL2_gfx
      - SDL2_gfx-devel
      - SDL2_image
      - SDL2_image-devel
      - SDL2_mixer
      - SDL2_mixer-devel
      - SDL2_net
      - SDL2_net-devel
      - SDL2_ttf
      - SDL2_ttf-devel
      - SDL2_Pango
      - SDL2_Pango-devel
      - SDL2_sound
      - SDL2_sound-devel

      # mingw 64
      - mingw64-gcc
      - mingw64-headers
      - mingw64-winpthreads
      - mingw64-crt

      # mingw 32
      - mingw32-gcc
      - mingw32-headers
      - mingw32-winpthreads
      - mingw32-crt

      # wine
      - wine-devel

      # zsh packages
      - zsh
      - autojump-zsh
      - zsh-autosuggestions
      - yt-dlp-zsh-completion
      - zsh-syntax-highlighting

    remove:
      - konsole
      - konsole-part



  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - org.openrgb.OpenRGB
        - dev.vencord.Vesktop
        - org.beeref.BeeRef
        - com.github.zocker_160.SyncThingy
        - com.github.tchx84.Flatseal
        - org.qbittorrent.qBittorrent
        - org.x.Warpinator
        - net.davidotek.pupgui2
        - com.usebottles.bottles
        - it.mijorus.gearlever
        - com.spotify.Client

        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

